### ISSUE TITLE
Incompatibility with CRM Early Bound Generator from Daryl Labar

### ISSUE THREAD

**Issue by MscrmTools** [macacq/PluginRegistration#1]
When running PluginRegistration from XrmToolBox with CRM Early Bound Generator plugin from Daryl Labar, there is an error about proxy types

![prterror](https://cloud.githubusercontent.com/assets/10774317/7025553/b5a3f328-dd44-11e4-99f7-426fed7b5fb6.png)

**Comment by macacq** [comment]
I'm on it! Thanks!

**Comment by daryllabar** [comment]
Interesting...  Did this ever get resolved?

**Comment by MscrmTools** [comment]
I have a possible fix in the upcoming version of XrmToolBox but I need two tools that use EarlyBound Entities to check it is working. I already have yours, @daryllabar, but need another one

**Comment by macacq** [comment]
This issue related to https://github.com/MscrmTools/XrmToolBox/issues/353 and https://github.com/MscrmTools/XrmToolBox/issues/445
